import { NextResponse } from 'next/server';

function getRandomAvatar() {
  const avatarSize = 128; // Size of the avatar (adjust as needed)
  const avatarId = Math.floor(Math.random() * 1000); // Random ID for avatar
  return `https://robohash.org/${avatarId}?set=set1&size=64x64`;
}

const data = {
  Influencers: [
    {
      id: 1,
      name: 'Shahrukh Khan',
      rating: 5,
      cost: 50000,
      follower: 250000,
      availability: false,
      gender: 'Male',
      avatar: getRandomAvatar(),
    },
    {
      id: 2,
      name: 'Kritika',
      rating: 4.2,
      cost: 20000,
      follower: 3000,
      availability: true,
      gender: 'Female',
      avatar: getRandomAvatar(),
    },
    {
      id: 3,
      name: 'Rahul',
      rating: 3.4,
      cost: 4050,
      follower: 9090,
      availability: true,
      gender: 'Male',
      avatar: getRandomAvatar(),
    },
    {
      id: 4,
      name: 'Ruhana',
      rating: 4.3,
      cost: 5699,
      follower: 9404,
      availability: true,
      gender: 'Female',
      avatar: getRandomAvatar(),
    },
    {
      id: 5,
      name: 'Salman Khan',
      rating: 3.4,
      cost: 4500,
      follower: 5893,
      availability: true,
      gender: 'Male',
      avatar: getRandomAvatar(),
    },
    {
      id: 6,
      name: 'Deepika Padukone',
      rating: 4.8,
      cost: 35000,
      follower: 120000,
      availability: true,
      gender: 'Female',
      avatar: getRandomAvatar(),
    },
    {
      id: 7,
      name: 'Ranbir Kapoor',
      rating: 4.1,
      cost: 30000,
      follower: 70000,
      availability: true,
      gender: 'Male',
      avatar: getRandomAvatar(),
    },
    {
      id: 8,
      name: 'Anushka Sharma',
      rating: 4.5,
      cost: 25000,
      follower: 85000,
      availability: true,
      gender: 'Female',
      avatar: getRandomAvatar(),
    },
    {
      id: 9,
      name: 'Varun Dhawan',
      rating: 3.9,
      cost: 18000,
      follower: 45000,
      availability: true,
      gender: 'Male',
      avatar: getRandomAvatar(),
    },
    {
      id: 10,
      name: 'Alia Bhatt',
      rating: 4.2,
      cost: 22000,
      follower: 60000,
      availability: true,
      gender: 'Female',
      avatar: getRandomAvatar(),
    },
    {
      id: 11,
      name: 'Ajay Devgan',
      rating: 4.0,
      cost: 28000,
      follower: 80000,
      availability: true,
      gender: 'Male',
      avatar: getRandomAvatar(),
    },
    {
      id: 12,
      name: 'Priyanka Chopra',
      rating: 4.6,
      cost: 32000,
      follower: 110000,
      availability: true,
      gender: 'Female',
      avatar: getRandomAvatar(),
    },
    {
      id: 13,
      name: 'Akshay Kumar',
      rating: 3.8,
      cost: 24000,
      follower: 70000,
      availability: true,
      gender: 'Male',
      avatar: getRandomAvatar(),
    },
    {
      id: 14,
      name: 'Katrina Kaif',
      rating: 4.1,
      cost: 29000,
      follower: 85000,
      availability: true,
      gender: 'Female',
      avatar: getRandomAvatar(),
    },
    {
      id: 15,
      name: 'Hrithik Roshan',
      rating: 4.4,
      cost: 31000,
      follower: 90000,
      availability: true,
      gender: 'Male',
      avatar: getRandomAvatar(),
    },
    {
      id: 16,
      name: 'Deepika Padukone',
      rating: 4.5,
      cost: 27000,
      follower: 75000,
      availability: true,
      gender: 'Female',
      avatar: getRandomAvatar(),
    },
    {
      id: 17,
      name: 'Amitabh Bachchan',
      rating: 4.3,
      cost: 26000,
      follower: 72000,
      availability: true,
      gender: 'Male',
      avatar: getRandomAvatar(),
    },
    {
      id: 18,
      name: 'Kangana Ranaut',
      rating: 3.9,
      cost: 23000,
      follower: 65000,
      availability: true,
      gender: 'Female',
      avatar: getRandomAvatar(),
    },
    {
      id: 19,
      name: 'Ranveer Singh',
      rating: 4.2,
      cost: 29000,
      follower: 80000,
      availability: true,
      gender: 'Male',
      avatar: getRandomAvatar(),
    },
    {
      id: 20,
      name: 'Ananya Panday',
      rating: 3.7,
      cost: 20000,
      follower: 50000,
      availability: true,
      gender: 'Female',
      avatar: getRandomAvatar(),
    },
  ],
};

export async function GET() {
  return NextResponse.json(data);
}
